just to make sure
Signed-off-by: maji <maji@himaji.xyz>

diff --git a/.github/workflows/dm-test.yaml b/.github/workflows/dm-test.yaml
--- a/.github/workflows/dm-test.yaml
+++ b/.github/workflows/dm-test.yaml
@@ -32,6 +32,8 @@ jobs:
           use-dotnet: true
           include-templates: false
           cache: true
+      - name: just to make sure
+        run: ls -la Polytoria/native/Luau.VM/linux/ || echo "Directory not found"
       - name: Test Datamodel
         run: |
           dotnet --version
